remote_theme: pmarsceill/just-the-docs
logo: "images/oc_logo.png"
footer_content: "<a href=\"https://github.com/ashleymcnamara/gophers\">Gopher artwork by Ashley McNamara</a> licensed under the <a href=\"https://creativecommons.org/licenses/by-nc-sa/4.0/\">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 License</a>"